import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker from '../dist/server/index.js';
import {dailyChallenge,medal,unlockedCourses} from '../web/challenges.js';
import {COURSES} from '../web/courses.js';
const sqlite=new DatabaseSync(':memory:');
for(const file of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
export const DB={prepare(sql){let args=[];return {bind(...a){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:r.changes}}}}},async batch(stmts){sqlite.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}};
export async function request(path,body,user='features'){const r=await worker.fetch(new Request('https://golf.test'+path,{method:body===undefined?'GET':'POST',headers:{'oai-authenticated-user-id':user,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}),{DB});return {status:r.status,body:await r.json()};}
for(const [score,m] of [[91,null],[90,'Bronze'],[82,'Bronze'],[81,'Silver'],[73,'Silver'],[72,'Gold']])assert.equal(medal(score),m);
for(const best of [{},{3:91},{3:90},{3:72,4:90}])assert.deepEqual(unlockedCourses(best),[0,1,2,3,4,5,6,7]);
async function complete(r,score,metrics=true,user='features'){let result;for(let h=r.next_hole;h<=r.end_hole;h++){result=await request('/api/rounds/'+r.id+'/holes',{hole:h,strokes:score, ...(metrics?{metrics:{putts:2,fairway:COURSES[r.course].holes[h].par>3?1:null,gir:1}}:{})},user);assert.equal(result.status,200);}return result;}
for(let course=4;course<8;course++)for(const mode of ['front','back','full'])assert.equal((await request('/api/rounds',{course,mode})).status,200);
let r=(await request('/api/rounds',{course:3,mode:'front'})).body.round;await complete(r,5);for(let course=4;course<8;course++)for(const mode of ['front','back','full'])assert.equal((await request('/api/rounds',{course,mode})).status,200);
r=(await request('/api/rounds',{course:3,mode:'full'})).body.round;await complete(r,5);
const p=(await request('/api/profile')).body.profile;assert.equal(p.courseBest[3],90);assert.equal(p.courseMedals[3],'Bronze');assert(p.unlockedCourses.includes(4));assert.deepEqual(p.unlockedCourses,[0,1,2,3,4,5,6,7]);
assert.equal((await request('/api/rounds',{course:4,mode:'full'},'stranger')).status,200);
let stats=(await request('/api/stats')).body.stats;assert.equal(stats.trackedHoles,27);assert.equal(stats.putts,54);assert.equal(stats.greens,27);
const before=JSON.stringify(stats),dailyA=(await request('/api/daily')).body.daily,dailyB=(await request('/api/daily',undefined,'stranger')).body.daily;assert.deepEqual(dailyA,dailyB);
assert.deepEqual(dailyA,dailyChallenge());assert.equal(dailyA.end-dailyA.start,2);
const startTokens=p.tokens;
r=(await request('/api/daily',{})).body.round;assert.deepEqual(r.daily,dailyA);const endpoint='/api/rounds/'+r.id+'/holes';
assert.equal((await request(endpoint,{hole:r.next_hole+1,strokes:4})).status,409);
assert.equal((await request(endpoint,{hole:r.next_hole,strokes:4,metrics:{putts:8,fairway:1,gir:1}})).status,400);
assert.equal((await request(endpoint,{hole:r.next_hole,strokes:4},'stranger')).status,404);
const result=await complete(r,3);assert.equal(result.body.dailyReward,50);assert.equal(result.body.profile.tokens,startTokens+50);
await request(endpoint,{hole:r.end_hole,strokes:3});assert.equal((await request('/api/profile')).body.profile.tokens,startTokens+50);
r=(await request('/api/daily',{})).body.round;const again=await complete(r,3);assert.equal(again.body.dailyReward,0);assert.equal(again.body.profile.tokens,startTokens+50);
assert.equal(JSON.stringify((await request('/api/stats')).body.stats),before);
assert.equal((await request('/api/daily')).body.reward,50);
assert.equal((await request('/api/stats',undefined,'stranger')).body.stats.trackedHoles,0);
const records=(await request('/api/records')).body.records;assert(records.every(r=>['full','front','back'].includes(r.mode)));
console.log('PASS medal thresholds, all-course access, partial-round exclusion, statistics, deterministic daily holes/weather, once-only rewards, retry safety, and account isolation.');
